[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ml_pipeline_automation"
version = "0.0.1"
description = "Default of Credit Card"
authors = [
  { name = "Alexey Teplayakov" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "black>=26.10.0",
    "catboost>=1.2.10",
    "fastapi",
    "flake8>=7.4.1",
    "ipython",
    "jupyterlab",
    "kagglehub>=1.0.2",
    "loguru",
    "matplotlib",
    "mlflow>=3.16.1",
    "notebook",
    "numpy",
    "optuna>=5.0.0",
    "pandas",
    "pandera[io,pandas]>=0.34.0",
    "pip",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "tqdm",
    "typer",
    "uvicorn",
]
requires-python = "~=3.13.0"


[tool.ruff]
line-length = 99
src = ["ml_pipeline_automation"]
include = ["pyproject.toml", "ml_pipeline_automation/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ml_pipeline_automation"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "black>=26.10.0",
    "dvc>=3.67.1",
    "flake8>=7.4.1",
    "great-expectations>=1.24.0",
]
